### ISSUE TITLE
Don't overwrite existing debian dir

### ISSUE THREAD

**Issue by ariscn** [nylas/make-deb#6]
Running `make-deb` when a `debian` sub-folder is present blows away that folder. This should at least prompt before doing so.

**Comment by systemizer** [comment]
Good idea :). Hopefully everyone is on version control, but for the one time someone isn't...

I've committed a fix: https://github.com/nylas/make-deb/commit/130610d1a187af76892cfa7a628974717d6f9645

You can expect this to be released in 0.0.5

Thanks for the help!
